/**
 * ORDS generated API for AUTOR
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NUMBER } from './nUMBER';
import { VARCHAR2 } from './vARCHAR2';


export interface SUBCATEGORIEITEM { 
    codSubcategorie?: NUMBER;
    codCategorie?: NUMBER;
    denumire?: VARCHAR2;
}
