/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AUTORITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "autor", description = "the autor API")
@RequestMapping(value = "/ords/{db}")
public interface AutorApi {


    @ApiOperation(value = "", nickname = "autorGet", notes = "Retrieve records from AUTOR", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/autor",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> autorGet(@PathVariable("db") String db);


    @ApiOperation(value = "", nickname = "autorIdDelete", notes = "Remove a record from AUTOR", response = AUTORITEM.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 204, message = "Deleted result.", response = AUTORITEM.class) })
    @RequestMapping(value = "/autor/{id}",
        produces = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<AUTORITEM> autorIdDelete(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "autorIdGet", notes = "Retrieve a record from AUTOR", response = AUTORITEM.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "The queried record.", response = AUTORITEM.class) })
    @RequestMapping(value = "/autor/{id}",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<AUTORITEM> autorIdGet(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "autorIdPut", notes = "Create or update a record on AUTOR", response = AUTORITEM.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "The successfully updated record.", response = AUTORITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = AUTORITEM.class) })
    @RequestMapping(value = "/autor/{id}",
        produces = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<AUTORITEM> autorIdPut(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody AUTORITEM payload);


    @ApiOperation(value = "", nickname = "autorPost", notes = "Create a new record on AUTOR", response = AUTORITEM.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 201, message = "The successfully created record.", response = AUTORITEM.class) })
    @RequestMapping(value = "/autor",
        produces = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<AUTORITEM> autorPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody AUTORITEM payload);

}
