/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CARTEITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "carte", description = "the carte API")
@RequestMapping(value = "/ords/{db}")
public interface CarteApi {

    @ApiOperation(value = "", nickname = "carteBatchloadPost", notes = "Create new records on CARTE", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/carte/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> carteBatchloadPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "carteGet", notes = "Retrieve records from CARTE", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/carte",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> carteGet(@PathVariable("db") String db);


    @ApiOperation(value = "", nickname = "carteIdDelete", notes = "Remove a record from CARTE", response = CARTEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = CARTEITEM.class) })
    @RequestMapping(value = "/carte/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<CARTEITEM> carteIdDelete(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "carteIdGet", notes = "Retrieve a record from CARTE", response = CARTEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = CARTEITEM.class) })
    @RequestMapping(value = "/carte/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CARTEITEM> carteIdGet(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "carteIdPut", notes = "Create or update a record on CARTE", response = CARTEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = CARTEITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = CARTEITEM.class) })
    @RequestMapping(value = "/carte/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<CARTEITEM> carteIdPut(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody CARTEITEM payload);


    @ApiOperation(value = "", nickname = "cartePost", notes = "Create a new record on CARTE", response = CARTEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = CARTEITEM.class) })
    @RequestMapping(value = "/carte",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<CARTEITEM> cartePost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody CARTEITEM payload);

}
