/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DONEAZAITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "doneaza", description = "the doneaza API")
@RequestMapping(value = "/ords/{db}")
public interface DoneazaApi {

    @ApiOperation(value = "", nickname = "doneazaBatchloadPost", notes = "Create new records on DONEAZA", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/doneaza/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> doneazaBatchloadPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "doneazaGet", notes = "Retrieve records from DONEAZA", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/doneaza",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> doneazaGet(@PathVariable("db") String db);


    @ApiOperation(value = "", nickname = "doneazaIdDelete", notes = "Remove a record from DONEAZA", response = DONEAZAITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = DONEAZAITEM.class) })
    @RequestMapping(value = "/doneaza/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<DONEAZAITEM> doneazaIdDelete(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "doneazaIdGet", notes = "Retrieve a record from DONEAZA", response = DONEAZAITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = DONEAZAITEM.class) })
    @RequestMapping(value = "/doneaza/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<DONEAZAITEM> doneazaIdGet(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "doneazaIdPut", notes = "Create or update a record on DONEAZA", response = DONEAZAITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = DONEAZAITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = DONEAZAITEM.class) })
    @RequestMapping(value = "/doneaza/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<DONEAZAITEM> doneazaIdPut(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody DONEAZAITEM payload);


    @ApiOperation(value = "", nickname = "doneazaPost", notes = "Create a new record on DONEAZA", response = DONEAZAITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = DONEAZAITEM.class) })
    @RequestMapping(value = "/doneaza",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<DONEAZAITEM> doneazaPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody DONEAZAITEM payload);

}
