/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.EMITEITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "emite", description = "the emite API")
@RequestMapping(value = "/ords/testuser2")
public interface EmiteApi {

    @ApiOperation(value = "", nickname = "emiteBatchloadPost", notes = "Create new records on EMITE", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/emite/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> emiteBatchloadPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "emiteGet", notes = "Retrieve records from EMITE", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/emite",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> emiteGet();


    @ApiOperation(value = "", nickname = "emiteIdDelete", notes = "Remove a record from EMITE", response = EMITEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = EMITEITEM.class) })
    @RequestMapping(value = "/emite/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<EMITEITEM> emiteIdDelete(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "emiteIdGet", notes = "Retrieve a record from EMITE", response = EMITEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = EMITEITEM.class) })
    @RequestMapping(value = "/emite/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<EMITEITEM> emiteIdGet(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "emiteIdPut", notes = "Create or update a record on EMITE", response = EMITEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = EMITEITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = EMITEITEM.class) })
    @RequestMapping(value = "/emite/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<EMITEITEM> emiteIdPut(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody EMITEITEM payload);


    @ApiOperation(value = "", nickname = "emitePost", notes = "Create a new record on EMITE", response = EMITEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = EMITEITEM.class) })
    @RequestMapping(value = "/emite",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<EMITEITEM> emitePost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody EMITEITEM payload);

}
