/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.FORMATADINITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "formata_din", description = "the formata_din API")
@RequestMapping(value = "/ords/{db}")
public interface FormataDinApi {

    @ApiOperation(value = "", nickname = "formataDinBatchloadPost", notes = "Create new records on FORMATA_DIN", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/formata_din/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> formataDinBatchloadPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "formataDinGet", notes = "Retrieve records from FORMATA_DIN", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/formata_din",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> formataDinGet(@PathVariable("db") String db);


    @ApiOperation(value = "", nickname = "formataDinIdDelete", notes = "Remove a record from FORMATA_DIN", response = FORMATADINITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = FORMATADINITEM.class) })
    @RequestMapping(value = "/formata_din/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<FORMATADINITEM> formataDinIdDelete(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "formataDinIdGet", notes = "Retrieve a record from FORMATA_DIN", response = FORMATADINITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = FORMATADINITEM.class) })
    @RequestMapping(value = "/formata_din/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<FORMATADINITEM> formataDinIdGet(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "formataDinIdPut", notes = "Create or update a record on FORMATA_DIN", response = FORMATADINITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = FORMATADINITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = FORMATADINITEM.class) })
    @RequestMapping(value = "/formata_din/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<FORMATADINITEM> formataDinIdPut(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody FORMATADINITEM payload);


    @ApiOperation(value = "", nickname = "formataDinPost", notes = "Create a new record on FORMATA_DIN", response = FORMATADINITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = FORMATADINITEM.class) })
    @RequestMapping(value = "/formata_din",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<FORMATADINITEM> formataDinPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody FORMATADINITEM payload);

}
