/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.FURNIZORITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "furnizor", description = "the furnizor API")
@RequestMapping(value = "/ords/testuser2")
public interface FurnizorApi {

    @ApiOperation(value = "", nickname = "furnizorBatchloadPost", notes = "Create new records on FURNIZOR", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/furnizor/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> furnizorBatchloadPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "furnizorGet", notes = "Retrieve records from FURNIZOR", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/furnizor",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> furnizorGet();


    @ApiOperation(value = "", nickname = "furnizorIdDelete", notes = "Remove a record from FURNIZOR", response = FURNIZORITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = FURNIZORITEM.class) })
    @RequestMapping(value = "/furnizor/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<FURNIZORITEM> furnizorIdDelete(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "furnizorIdGet", notes = "Retrieve a record from FURNIZOR", response = FURNIZORITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = FURNIZORITEM.class) })
    @RequestMapping(value = "/furnizor/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<FURNIZORITEM> furnizorIdGet(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "furnizorIdPut", notes = "Create or update a record on FURNIZOR", response = FURNIZORITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = FURNIZORITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = FURNIZORITEM.class) })
    @RequestMapping(value = "/furnizor/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<FURNIZORITEM> furnizorIdPut(@Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody FURNIZORITEM payload);


    @ApiOperation(value = "", nickname = "furnizorPost", notes = "Create a new record on FURNIZOR", response = FURNIZORITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = FURNIZORITEM.class) })
    @RequestMapping(value = "/furnizor",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<FURNIZORITEM> furnizorPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody FURNIZORITEM payload);

}
