/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.LEGITIMATIEITEM;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-16T16:00:11.731Z")

@Validated
@Api(value = "legitimatie", description = "the legitimatie API")
@RequestMapping(value = "/ords/{db}")
public interface LegitimatieApi {

    @ApiOperation(value = "", nickname = "legitimatieBatchloadPost", notes = "Create new records on LEGITIMATIE", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The status of the processed records.", response = String.class) })
    @RequestMapping(value = "/legitimatie/batchload",
        produces = { "text/plain" }, 
        consumes = { "text/csv" },
        method = RequestMethod.POST)
    ResponseEntity<String> legitimatieBatchloadPost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody Object payload);


    @ApiOperation(value = "", nickname = "legitimatieGet", notes = "Retrieve records from LEGITIMATIE", response = Object.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = Object.class) })
    @RequestMapping(value = "/legitimatie",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> legitimatieGet(@PathVariable("db") String db);


    @ApiOperation(value = "", nickname = "legitimatieIdDelete", notes = "Remove a record from LEGITIMATIE", response = LEGITIMATIEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Deleted result.", response = LEGITIMATIEITEM.class) })
    @RequestMapping(value = "/legitimatie/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<LEGITIMATIEITEM> legitimatieIdDelete(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "legitimatieIdGet", notes = "Retrieve a record from LEGITIMATIE", response = LEGITIMATIEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The queried record.", response = LEGITIMATIEITEM.class) })
    @RequestMapping(value = "/legitimatie/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<LEGITIMATIEITEM> legitimatieIdGet(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "", nickname = "legitimatieIdPut", notes = "Create or update a record on LEGITIMATIE", response = LEGITIMATIEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The successfully updated record.", response = LEGITIMATIEITEM.class),
        @ApiResponse(code = 201, message = "The successfully created record.", response = LEGITIMATIEITEM.class) })
    @RequestMapping(value = "/legitimatie/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<LEGITIMATIEITEM> legitimatieIdPut(@PathVariable("db") String db, @Pattern(regexp="^[^/]+$") @ApiParam(value = "implicit",required=true) @PathVariable("id") String id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody LEGITIMATIEITEM payload);


    @ApiOperation(value = "", nickname = "legitimatiePost", notes = "Create a new record on LEGITIMATIE", response = LEGITIMATIEITEM.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "The successfully created record.", response = LEGITIMATIEITEM.class) })
    @RequestMapping(value = "/legitimatie",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<LEGITIMATIEITEM> legitimatiePost(@PathVariable("db") String db, @ApiParam(value = "" ,required=true )  @Valid @RequestBody LEGITIMATIEITEM payload);

}
